# docker-compose.yml
version: '3.1'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
