name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - name: pub get
        run: |
          cd app
          flutter pub get
      - name: build web
        run: |
          cd app
          flutter pub run build_runner build --delete-conflicting-outputs
          echo ${{FLUTTER_WEB_FIREBASE_CONFIG_JS_CONTENT}} > web/credentials/firebase.config.js
          flutter build web --release
      - name: deploy
        run: |
          cd app
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          # git config --global user.email your_email 
          # git config --global user.name your_name 
          git config --global user.email woojoo@softmarshmallow.com
          git config --global user.name softmarshmallow
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/softmarshmallow/robbin.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
